### ISSUE TITLE
no plot shown

### ISSUE THREAD

**Issue by drobwolf** [jktr/matplotlib-backend-notcurses#1]
Hi, I've tried installing according to the instructions on pypi and also via cloning your repo into the site-packages directory. I try to run the example you have outlined on your splash page. 

$ export MPLBACKEND='module://matplotlib-backend-notcurses'
$ python -i
>>> import numpy as np; import pandas as pd
>>> n = 10000
>>> df = pd.DataFrame({'x': np.random.randn(n),
                       'y': np.random.randn(n)})
>>> df.plot.hexbin(x='x', y='y', gridsize=20)
<plot is shown>

However, my results copied from ipython below illustrate what is happening to me, no graphic is shown, instead I get the following output below.

In [5]: df.plot.hexbin(x='x', y='y', gridsize=20)
Out[5]: <AxesSubplot: xlabel='x', ylabel='y'>

**Comment by jktr** [comment]
There's some known breakage due to how backends are initialized in matplotlib 3.6. This should get fixed relatively soon.

See https://github.com/jktr/matplotlib-backend-kitty/issues/6

**Comment by jktr** [comment]
The mentioned fix is up. Please re-open this issue if that doesn't solve it for you and mention your python/matplotlib/kitty versions.
